SELECT * FROM EMP;
-- 복사테이블 만들기(데이터와 구조)
CREATE TABLE EMP01
AS SELECT * FROM EMP;
SELECT * FROM EMP01;
-- 복사테이블 만들기(구조만 복사)
SELECT * FROM EMP WHERE 1 = 0; -- 1=0 FALSE로 데이터를 가져오지 못함
CREATE TABLE EMP02
AS SELECT * FROM EMP WHERE 1=0; -- 테이블의 구조만 복사해서 만들어짐..
SELECT * FROM EMP02; 
-- EX) DEPT 테이블을 이용해서 DEPT01로 데이터와 구조 복사, DEPT02로 구조만 복사한
--   테이블을 만드세요..
CREATE TABLE DEPT01
AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;
CREATE TABLE DEPT02
AS SELECT * FROM DEPT WHERE 1=0;
SELECT * FROM DEPT02;

SELECT * FROM EMP01;

-- EMP01(JOB, ENAME), EMP02, DEPT01(DNAME,LOC), DEPT02  
--   ==> VARCHAR2(50) 변경
/*
EX) 일부분 구조로 데이터를 처리하는 테이블 생성
 * */
SELECT EMPNO NO, ENAME NAME, JOB, SAL
FROM EMP;
CREATE TABLE EMP03
AS SELECT EMPNO NO, ENAME NAME, JOB, SAL
FROM EMP;
SELECT * FROM EMP03;
SELECT * FROM EMP;
-- EX) EMPNO, ENAME, JOB, DEPTNO로 복사테이블(EMP04)을 만들어 보세요..
CREATE TABLE EMP04
AS SELECT EMPNO, ENAME, JOB, DEPTNO
	FROM EMP
   WHERE DEPTNO = 10; -- 부서번호과 10인 경우에 데이터를 테이블로 만들어 준다.
SELECT * FROM EMP04;
DROP TABLE EMP04;
-- EX) 사원정보중에 급여(SAL)가 2000이상인 부서번호(DEPTNO), 
--   사원번호(EMPNO), 사원명(ENAME), 급여(SAL)를 EMP05테이블로 만드세요









SELECT EMPNO, ENAME, JOB, DEPTNO
	FROM EMP
   WHERE DEPTNO = 10;




