SELECT BOARD_SEQ.NEXTVAL FROM DUAL;		
SELECT BOARD_SEQ.CURRVAL FROM DUAL;

CREATE TABLE PRODUCT(
    NO INT PRIMARY KEY,
    NAME VARCHAR2(50),
    PRICE INT,
    CNT INT
);
CREATE SEQUENCE PRODUCT_SEQ;
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '사과',2000,3);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '바나나',4000,1);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '딸기',12000,5);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL, '오렌지',3000,2);
SELECT * FROM PRODUCT ORDER BY NO;
UPDATE PRODUCT
   SET NAME = '키위',
       PRICE = 2000,
       CNT = 2
  WHERE NO = 1;
/*
SELECT * FROM PRODUCT ORDER BY NO

UPDATE PRODUCT
   SET NAME = :name,
       PRICE = :price,
       CNT = :cnt
  WHERE NO = :no
 

 * */