
SELECT * FROM STUDENT12;
INSERT INTO STUDENT12 VALUES(1000,'홍길동',25);
CREATE TABLE STUDENT12_SUBJECT(
	SUBJECT VARCHAR(50),
	GRADE NUMBER(1,0),
	SID NUMBER CONSTRAINT STUDENT12_SUBJECT_SID_FK REFERENCES STUDENT12(SID)
);
INSERT INTO STUDENT12_SUBJECT VALUES('컴퓨터공학',3,1000);
SELECT * FROM STUDENT12_SUBJECT;