/*
# NON EQUAL JOIN
1. 조인하는 두 개의 테이블의 컬럼 값이 동일하지 않지만, 범위를 정하거나 특정한 형식으로
	조인을 할 수 있을 때, 사용하는 JOIN구문을 말한다.
	EX) 사원의 급여는 등급테이블의 특정컬럼과 정확하게 동일하지 않지만, 범위를 지정해서
		조인하는 것은 가능 하다..
		
 * */
SELECT * FROM SALGRADE;
-- 사원의 급여를 등급별로 분류해서 조인하여 출력
SELECT ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

CREATE TABLE STUDENTS2 (
    STUDENT_ID INT ,     -- 학생 ID
    STUDENT_NAME VARCHAR(100),      -- 학생 이름
    GRADE NUMBER(5, 2)             -- 학생 점수
);

INSERT INTO STUDENTS2 (STUDENT_ID, STUDENT_NAME, GRADE) VALUES(1, 'Alice', 85.5);     -- Alice는 85.5점
INSERT INTO STUDENTS2 (STUDENT_ID, STUDENT_NAME, GRADE) VALUES(2, 'Bob', 70.0);     -- Alice는 85.5점
INSERT INTO STUDENTS2 (STUDENT_ID, STUDENT_NAME, GRADE) VALUES(3, 'Charlie', 92.3);     -- Alice는 85.5점
INSERT INTO STUDENTS2 (STUDENT_ID, STUDENT_NAME, GRADE) VALUES(4, 'David', 65.0);     -- Alice는 85.5점
INSERT INTO STUDENTS2 (STUDENT_ID, STUDENT_NAME, GRADE) VALUES(5, 'Eva', 78.4);     -- Alice는 85.5점

CREATE TABLE GRADE_TABLE (
    GRADE_LEVEL INT PRIMARY KEY,  -- 등급 레벨
    MIN_SCORE NUMBER(5, 2),      -- 최소 점수
    MAX_SCORE NUMBER(5, 2)      -- 최대 점수
);

INSERT INTO GRADE_TABLE (GRADE_LEVEL, MIN_SCORE, MAX_SCORE) VALUES(1, 0, 59.99);   -- 1등급: 0 ~ 59.99점
INSERT INTO GRADE_TABLE (GRADE_LEVEL, MIN_SCORE, MAX_SCORE) VALUES(2, 60, 69.99);   -- 1등급: 0 ~ 59.99점
INSERT INTO GRADE_TABLE (GRADE_LEVEL, MIN_SCORE, MAX_SCORE) VALUES(3, 70, 79.99);   -- 1등급: 0 ~ 59.99점
INSERT INTO GRADE_TABLE (GRADE_LEVEL, MIN_SCORE, MAX_SCORE) VALUES(4, 80, 89.99);   -- 1등급: 0 ~ 59.99점
INSERT INTO GRADE_TABLE (GRADE_LEVEL, MIN_SCORE, MAX_SCORE) VALUES(5, 90, 100);   -- 1등급: 0 ~ 59.99점
SELECT * FROM STUDENTS2;  -- STUDENT_NAME, GRADE
SELECT * FROM GRADE_TABLE; 
SELECT  STUDENT_NAME, GRADE, GRADE_LEVEL, MIN_SCORE, MAX_SCORE
FROM STUDENTS2 S, GRADE_TABLE G
WHERE S.GRADE BETWEEN MIN_SCORE AND MAX_SCORE;
-- EX) STUDENTS2테이블과 GRADE_TABLE를 NON EQUAL JOIN으로 처리하세요.
/*
SELECT ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
**/


